language: 'node_js'
node_js:
 - '8'
matrix:
  include:
    - node_js: '8'
      env: TASK=LINT
    - node_js: '8'
      env: TASK=TEST
install:
  - npm install
script:
  - if [ "$TASK" = "LINT" ]; then npm run lint; fi
  - if [ "$TASK" = "TEST" ]; then npm run test; fi
